### ISSUE TITLE
Using DQN

### ISSUE THREAD

**Issue by hydr93** [karpathy/reinforcejs#13]
Hello,

In the example library usage, the environment is created with number of states and also maximum number of actions possible. 

For example, if I have 5 possible states, which is defined with 2 values, and 3 possible actions, which is also defined with 2 values, what should be the relevant variables of environment object? Moreover, what should be the given state array in 'act(state)' method.

I normally have more states and actions however I couldn't get the general idea behind it.

P.S. I know that this question is more suitable for StackOverFlow, however I also think that it would be beneficial for other new people.

**Comment by gringrant** [comment]
In all the examples I have seen DQN, the screen position was fixed, and the AI was fed the pixel data or xy coords (e.g. Atari Breakout Example, Puck World) or the world was given to the AI from it's perspective (e.g. Super Mario, Water World). In some examples the AI was fed additional data such as velocity or xy coords. The outputs are usually velocity controls. For more complex things I (note:not well tested) convert the output to binary, y=x.toString(2).split(""), so for example y[0] would be button zero that the AI controls.

Note: I am not an AI expert, so correct me if I am wrong
