### ISSUE TITLE
Could throw error when input array mismatches getNumStates

### ISSUE THREAD

**Issue by mryellow** [karpathy/reinforcejs#4]
I had neglected to set `getNumStates` yet nothing complains.

Guess it's an extra check every time you give an input array to `act`, a comparison of sizes in each call to `setFrom` would likely be over the top... 

Could validate in `Agent.forward` before passing to `DQNAgent.act`, but then if doing it there, then why not in `act`.

Maybe there is a solution in checking the sizes _once_ for the first call to `act`?

**Comment by mryellow** [comment]
Feel free to "wontfix" this if I should be more careful in future ;-)

If it could be checked at the constructor it would make sense, but hacking in a switch condition to disable validation after the first call isn't too pretty.

**Comment by karpathy** [comment]
Thanks, you're right this should be validated, but right now that would be somewhat ugly, since it would have to be replicated in every single agent. Lets not worry about it for now :) Thanks!
